<?php

// autoload_real.php @generated by Composer

<<<<<<< HEAD
class ComposerAutoloaderInit4cef7e03206c71c22dbfbfcd47098f7c
=======
<<<<<<< HEAD
class ComposerAutoloaderInit02aa2b2bb9ea721f52cce11b77f65b3d
=======
<<<<<<< HEAD
class ComposerAutoloaderInitb0200717217495ad811e0d67533a1302
=======
<<<<<<< HEAD
class ComposerAutoloaderInit91750e95f2b30d4ad9c0e91acb52a028
=======
class ComposerAutoloaderInit5df15e3a090e0bf0225f63101ba06976
>>>>>>> 5886d1baa4daf85cba795085b5f687c80898f98e
>>>>>>> b47e28794f4ada0b2f41405dd11295797f0ab85b
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
>>>>>>> 81fc401745b988ca80ab15efab03fb1c940e6445
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

<<<<<<< HEAD
        spl_autoload_register(array('ComposerAutoloaderInit4cef7e03206c71c22dbfbfcd47098f7c', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit4cef7e03206c71c22dbfbfcd47098f7c', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit4cef7e03206c71c22dbfbfcd47098f7c::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInit4cef7e03206c71c22dbfbfcd47098f7c::$files;
=======
<<<<<<< HEAD
        spl_autoload_register(array('ComposerAutoloaderInit02aa2b2bb9ea721f52cce11b77f65b3d', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit02aa2b2bb9ea721f52cce11b77f65b3d', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit02aa2b2bb9ea721f52cce11b77f65b3d::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInit02aa2b2bb9ea721f52cce11b77f65b3d::$files;
=======
<<<<<<< HEAD
        spl_autoload_register(array('ComposerAutoloaderInitb0200717217495ad811e0d67533a1302', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitb0200717217495ad811e0d67533a1302', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitb0200717217495ad811e0d67533a1302::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInitb0200717217495ad811e0d67533a1302::$files;
=======
<<<<<<< HEAD
        spl_autoload_register(array('ComposerAutoloaderInit91750e95f2b30d4ad9c0e91acb52a028', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit91750e95f2b30d4ad9c0e91acb52a028', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit91750e95f2b30d4ad9c0e91acb52a028::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInit91750e95f2b30d4ad9c0e91acb52a028::$files;
>>>>>>> b47e28794f4ada0b2f41405dd11295797f0ab85b
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
>>>>>>> 81fc401745b988ca80ab15efab03fb1c940e6445
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
        spl_autoload_register(array('ComposerAutoloaderInit5df15e3a090e0bf0225f63101ba06976', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit5df15e3a090e0bf0225f63101ba06976', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        \Composer\Autoload\ComposerStaticInit5df15e3a090e0bf0225f63101ba06976::getInitializer($loader)();

        $loader->register(true);

        $includeFiles = \Composer\Autoload\ComposerStaticInit5df15e3a090e0bf0225f63101ba06976::$files;
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire5df15e3a090e0bf0225f63101ba06976($fileIdentifier, $file);
>>>>>>> 5886d1baa4daf85cba795085b5f687c80898f98e
>>>>>>> b47e28794f4ada0b2f41405dd11295797f0ab85b
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
>>>>>>> 81fc401745b988ca80ab15efab03fb1c940e6445
        }

        return $loader;
    }
}
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======

/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire5df15e3a090e0bf0225f63101ba06976($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }
}
>>>>>>> 5886d1baa4daf85cba795085b5f687c80898f98e
>>>>>>> b47e28794f4ada0b2f41405dd11295797f0ab85b
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
>>>>>>> 81fc401745b988ca80ab15efab03fb1c940e6445
