<?php

// autoload_real.php @generated by Composer

<<<<<<< HEAD
class ComposerAutoloaderInitdbc0044e500ab0f87409a07b60a3b828
=======
class ComposerAutoloaderInit2fb07ac95b437735ec9a7009ee8df744
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

<<<<<<< HEAD
        spl_autoload_register(array('ComposerAutoloaderInitdbc0044e500ab0f87409a07b60a3b828', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitdbc0044e500ab0f87409a07b60a3b828', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitdbc0044e500ab0f87409a07b60a3b828::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInitdbc0044e500ab0f87409a07b60a3b828::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
=======
        spl_autoload_register(array('ComposerAutoloaderInit2fb07ac95b437735ec9a7009ee8df744', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit2fb07ac95b437735ec9a7009ee8df744', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        \Composer\Autoload\ComposerStaticInit2fb07ac95b437735ec9a7009ee8df744::getInitializer($loader)();

        $loader->register(true);

        $includeFiles = \Composer\Autoload\ComposerStaticInit2fb07ac95b437735ec9a7009ee8df744::$files;
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire2fb07ac95b437735ec9a7009ee8df744($fileIdentifier, $file);
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
        }

        return $loader;
    }
}
<<<<<<< HEAD
=======

/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire2fb07ac95b437735ec9a7009ee8df744($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }
}
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
