<?php

// autoload.php @generated by Composer

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> b47e28794f4ada0b2f41405dd11295797f0ab85b
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    trigger_error(
        $err,
        E_USER_ERROR
    );
}

require_once __DIR__ . '/composer/autoload_real.php';

<<<<<<< HEAD
return ComposerAutoloaderInit02aa2b2bb9ea721f52cce11b77f65b3d::getLoader();
=======
<<<<<<< HEAD
return ComposerAutoloaderInitb0200717217495ad811e0d67533a1302::getLoader();
=======
return ComposerAutoloaderInit91750e95f2b30d4ad9c0e91acb52a028::getLoader();
=======
require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit5df15e3a090e0bf0225f63101ba06976::getLoader();
>>>>>>> 5886d1baa4daf85cba795085b5f687c80898f98e
>>>>>>> b47e28794f4ada0b2f41405dd11295797f0ab85b
>>>>>>> cfc45212359e3c31e90a15df610051b13d41f46e
